# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasknova < Formula
  desc "A CLI task manager for organizing tasks and notes"
  homepage "https://github.com/joaaomanooel/cli-tasknova"
  version "1.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.18/tasknova_1.0.18_macOS_amd64.tar.gz"
      sha256 "58188cbd3e0edd9251962a530ee19a901e03d2280e11ee96711e54a456f537a7"

      def install
        bin.install "tasknova"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.18/tasknova_1.0.18_macOS_arm64.tar.gz"
      sha256 "e0e5ec8f042e3dd9d71e0c288de4801ed071aa7bb2f6bc7489cbdf26a96daa53"

      def install
        bin.install "tasknova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.18/tasknova_1.0.18_linux_amd64.tar.gz"
      sha256 "82d4133fa269596ecf79fec7decfdde62c75c27766f844bb8f0a11f9dc787762"
      def install
        bin.install "tasknova"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.18/tasknova_1.0.18_linux_arm64.tar.gz"
      sha256 "88184ea798128b6ec2031d507b8d7f5dcc062904ac405e1d2b281443e629e8f1"
      def install
        bin.install "tasknova"
      end
    end
  end

  test do
    system "#{bin}/tasknova --version"
  end
end
