# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasknova < Formula
  desc "A CLI task manager for organizing tasks and notes"
  homepage "https://github.com/joaaomanooel/cli-tasknova"
  version "1.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.13/tasknova_1.0.13_macOS_amd64.tar.gz"
      sha256 "f610f026da9ccae57d2a9044168d44adcfc76d4c0d339215c9048b7e4d54909a"

      def install
        bin.install "tasknova"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.13/tasknova_1.0.13_macOS_arm64.tar.gz"
      sha256 "1cfa42b2882ea72b7b6934c19fa42bc0d9f126baef85c7119aa512948cda36f3"

      def install
        bin.install "tasknova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.13/tasknova_1.0.13_linux_amd64.tar.gz"
      sha256 "d8cf8ceb21d737d569dea18cae95a707a88d081927396f0e9d60244c320dae77"
      def install
        bin.install "tasknova"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/joaaomanooel/cli-tasknova/releases/download/v1.0.13/tasknova_1.0.13_linux_arm64.tar.gz"
      sha256 "0130f9fd5379687b3c76fa8d1e3b85989c4515a65f00d8acf473ac6b983719f3"
      def install
        bin.install "tasknova"
      end
    end
  end

  test do
    system "#{bin}/tasknova --version"
  end
end
